PREFIX sbol2: <http://sbols.org/v2#>
PREFIX biopax: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbi: <http://http://www.ncbi.nlm.nih.gov#>
SELECT  (count(distinct ?ComponentDefinition) as ?Count) 	
WHERE
{
?ComponentDefinition a sbol2:ComponentDefinition .
  OPTIONAL { ?ComponentDefinition dcterms:title ?Name}  
    %s
}